theme: jekyll-theme-dinky
logo: https://avatars0.githubusercontent.com/u/46445292
title: preferans-engine-js
description: preferans game engine
show_downloads: "true"
include:
  - "_*_.html"
  - "_*_.*.html"